[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "largest_prod_grid"
authors = [{name = "Christina", email = "christina@example.com"}]
dynamic = ["version", "description"]
